name: Build Wheel for Windows

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Wheel (Windows, Linux Python 3.12)
    runs-on: linux-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build wheel

      - name: Build wheel
        run: python -m build --wheel

      - name: Upload wheel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: py-find-1st-wheel
          path: dist/*.whl
